# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataset_wizard.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_DatasetWizardDialog(object):
    def setupUi(self, DatasetWizardDialog):
        DatasetWizardDialog.setObjectName("DatasetWizardDialog")
        DatasetWizardDialog.resize(586, 290)
        DatasetWizardDialog.setSizeGripEnabled(False)
        self.gridLayout_2 = QtWidgets.QGridLayout(DatasetWizardDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tfidfGroupbox = QtWidgets.QGroupBox(DatasetWizardDialog)
        self.tfidfGroupbox.setObjectName("tfidfGroupbox")
        self.formLayout = QtWidgets.QFormLayout(self.tfidfGroupbox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.tfidfGroupbox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.vocabSize = QtWidgets.QSpinBox(self.tfidfGroupbox)
        self.vocabSize.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.vocabSize.setMinimum(2500)
        self.vocabSize.setMaximum(100000)
        self.vocabSize.setSingleStep(2500)
        self.vocabSize.setProperty("value", 10000)
        self.vocabSize.setObjectName("vocabSize")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.vocabSize)
        self.label_2 = QtWidgets.QLabel(self.tfidfGroupbox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.stopwordsChoice = QtWidgets.QComboBox(self.tfidfGroupbox)
        self.stopwordsChoice.setObjectName("stopwordsChoice")
        self.stopwordsChoice.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.stopwordsChoice)
        self.gridLayout_2.addWidget(self.tfidfGroupbox, 1, 0, 1, 1)
        self.dataGroupbox = QtWidgets.QGroupBox(DatasetWizardDialog)
        self.dataGroupbox.setMaximumSize(QtCore.QSize(16777215, 1666))
        self.dataGroupbox.setObjectName("dataGroupbox")
        self.formLayout_3 = QtWidgets.QFormLayout(self.dataGroupbox)
        self.formLayout_3.setObjectName("formLayout_3")
        self.chooseDirectoryButton = QtWidgets.QPushButton(self.dataGroupbox)
        self.chooseDirectoryButton.setDefault(True)
        self.chooseDirectoryButton.setObjectName("chooseDirectoryButton")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.chooseDirectoryButton)
        self.directoryChoiceStatus = QtWidgets.QLabel(self.dataGroupbox)
        self.directoryChoiceStatus.setObjectName("directoryChoiceStatus")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.directoryChoiceStatus)
        self.label_3 = QtWidgets.QLabel(self.dataGroupbox)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.outputName = QtWidgets.QLineEdit(self.dataGroupbox)
        self.outputName.setObjectName("outputName")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.outputName)
        self.gridLayout_2.addWidget(self.dataGroupbox, 0, 0, 1, 1)
        self.createDatasetButton = QtWidgets.QPushButton(DatasetWizardDialog)
        self.createDatasetButton.setObjectName("createDatasetButton")
        self.gridLayout_2.addWidget(self.createDatasetButton, 2, 0, 1, 1)
        self.expandingGridLayout = QtWidgets.QGridLayout()
        self.expandingGridLayout.setObjectName("expandingGridLayout")
        self.progressBar = QtWidgets.QProgressBar(DatasetWizardDialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.expandingGridLayout.addWidget(self.progressBar, 0, 0, 1, 1)
        self.statusMessage = QtWidgets.QLabel(DatasetWizardDialog)
        self.statusMessage.setObjectName("statusMessage")
        self.expandingGridLayout.addWidget(self.statusMessage, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.expandingGridLayout, 3, 0, 1, 1)

        self.retranslateUi(DatasetWizardDialog)
        QtCore.QMetaObject.connectSlotsByName(DatasetWizardDialog)

    def retranslateUi(self, DatasetWizardDialog):
        _translate = QtCore.QCoreApplication.translate
        DatasetWizardDialog.setWindowTitle(_translate("DatasetWizardDialog", "Create a new dataset"))
        self.tfidfGroupbox.setTitle(_translate("DatasetWizardDialog", "TF-IDF Parameters"))
        self.label.setText(_translate("DatasetWizardDialog", "Vocabulary size"))
        self.label_2.setText(_translate("DatasetWizardDialog", "Stopwords"))
        self.stopwordsChoice.setItemText(0, _translate("DatasetWizardDialog", "english"))
        self.dataGroupbox.setTitle(_translate("DatasetWizardDialog", "Data"))
        self.chooseDirectoryButton.setText(_translate("DatasetWizardDialog", "Choose directory"))
        self.directoryChoiceStatus.setText(_translate("DatasetWizardDialog", "No directory chosen"))
        self.label_3.setText(_translate("DatasetWizardDialog", "Output name"))
        self.createDatasetButton.setText(_translate("DatasetWizardDialog", "Create dataset"))
        self.statusMessage.setText(_translate("DatasetWizardDialog", "Waiting for start..."))
