# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fetch_dataset_wizard.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_FetchDatasetDialog(object):
    def setupUi(self, FetchDatasetDialog):
        FetchDatasetDialog.setObjectName("FetchDatasetDialog")
        FetchDatasetDialog.resize(498, 264)
        FetchDatasetDialog.setSizeGripEnabled(False)
        self.gridLayout_2 = QtWidgets.QGridLayout(FetchDatasetDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.expandingGridLayout = QtWidgets.QGridLayout()
        self.expandingGridLayout.setObjectName("expandingGridLayout")
        self.statusMessage = QtWidgets.QLabel(FetchDatasetDialog)
        self.statusMessage.setObjectName("statusMessage")
        self.expandingGridLayout.addWidget(self.statusMessage, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.expandingGridLayout, 3, 0, 1, 1)
        self.closeButton = QtWidgets.QPushButton(FetchDatasetDialog)
        self.closeButton.setEnabled(False)
        self.closeButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.closeButton.setObjectName("closeButton")
        self.gridLayout_2.addWidget(self.closeButton, 3, 1, 1, 1)
        self.dataGroupbox = QtWidgets.QGroupBox(FetchDatasetDialog)
        self.dataGroupbox.setMaximumSize(QtCore.QSize(16777215, 1666))
        self.dataGroupbox.setObjectName("dataGroupbox")
        self.formLayout_3 = QtWidgets.QFormLayout(self.dataGroupbox)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_3 = QtWidgets.QLabel(self.dataGroupbox)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.outputName = QtWidgets.QLineEdit(self.dataGroupbox)
        self.outputName.setObjectName("outputName")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.outputName)
        self.label_4 = QtWidgets.QLabel(self.dataGroupbox)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.datasetName = QtWidgets.QComboBox(self.dataGroupbox)
        self.datasetName.setObjectName("datasetName")
        self.datasetName.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.datasetName)
        self.gridLayout_2.addWidget(self.dataGroupbox, 0, 0, 1, 2)
        self.tfidfGroupbox = QtWidgets.QGroupBox(FetchDatasetDialog)
        self.tfidfGroupbox.setObjectName("tfidfGroupbox")
        self.formLayout = QtWidgets.QFormLayout(self.tfidfGroupbox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.tfidfGroupbox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.vocabSize = QtWidgets.QSpinBox(self.tfidfGroupbox)
        self.vocabSize.setMinimum(2500)
        self.vocabSize.setMaximum(100000)
        self.vocabSize.setSingleStep(2500)
        self.vocabSize.setProperty("value", 10000)
        self.vocabSize.setObjectName("vocabSize")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.vocabSize)
        self.label_2 = QtWidgets.QLabel(self.tfidfGroupbox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.stopwordsChoice = QtWidgets.QComboBox(self.tfidfGroupbox)
        self.stopwordsChoice.setObjectName("stopwordsChoice")
        self.stopwordsChoice.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.stopwordsChoice)
        self.gridLayout_2.addWidget(self.tfidfGroupbox, 1, 0, 1, 2)
        self.createDatasetButton = QtWidgets.QPushButton(FetchDatasetDialog)
        self.createDatasetButton.setObjectName("createDatasetButton")
        self.gridLayout_2.addWidget(self.createDatasetButton, 2, 0, 1, 2)

        self.retranslateUi(FetchDatasetDialog)
        QtCore.QMetaObject.connectSlotsByName(FetchDatasetDialog)

    def retranslateUi(self, FetchDatasetDialog):
        _translate = QtCore.QCoreApplication.translate
        FetchDatasetDialog.setWindowTitle(_translate("FetchDatasetDialog", "Fetch a new dataset"))
        self.statusMessage.setText(_translate("FetchDatasetDialog", "Waiting for start..."))
        self.closeButton.setText(_translate("FetchDatasetDialog", "Close"))
        self.dataGroupbox.setTitle(_translate("FetchDatasetDialog", "Data"))
        self.label_3.setText(_translate("FetchDatasetDialog", "Output name"))
        self.outputName.setText(_translate("FetchDatasetDialog", "20ng"))
        self.label_4.setText(_translate("FetchDatasetDialog", "Choose the dataset"))
        self.datasetName.setItemText(0, _translate("FetchDatasetDialog", "20ng"))
        self.tfidfGroupbox.setTitle(_translate("FetchDatasetDialog", "TF-IDF Parameters"))
        self.label.setText(_translate("FetchDatasetDialog", "Vocabulary size"))
        self.label_2.setText(_translate("FetchDatasetDialog", "Stopwords"))
        self.stopwordsChoice.setItemText(0, _translate("FetchDatasetDialog", "english"))
        self.createDatasetButton.setText(_translate("FetchDatasetDialog", "Fetch dataset"))
