# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'semhash_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(865, 944)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.datasetsLabel = QtWidgets.QLabel(self.centralwidget)
        self.datasetsLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.datasetsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.datasetsLabel.setObjectName("datasetsLabel")
        self.gridLayout.addWidget(self.datasetsLabel, 0, 0, 1, 1)
        self.datasetList = QtWidgets.QListWidget(self.centralwidget)
        self.datasetList.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.datasetList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.datasetList.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.datasetList.setObjectName("datasetList")
        self.gridLayout.addWidget(self.datasetList, 1, 0, 1, 1)
        self.modelList = QtWidgets.QListWidget(self.centralwidget)
        self.modelList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.modelList.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.modelList.setAlternatingRowColors(False)
        self.modelList.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.modelList.setObjectName("modelList")
        self.gridLayout.addWidget(self.modelList, 1, 1, 1, 1)
        self.modelsLabel = QtWidgets.QLabel(self.centralwidget)
        self.modelsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.modelsLabel.setObjectName("modelsLabel")
        self.gridLayout.addWidget(self.modelsLabel, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 865, 26))
        self.menubar.setObjectName("menubar")
        self.menuNew_dataset = QtWidgets.QMenu(self.menubar)
        self.menuNew_dataset.setObjectName("menuNew_dataset")
        self.menuNew_model = QtWidgets.QMenu(self.menubar)
        self.menuNew_model.setObjectName("menuNew_model")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuNew_dataset.menuAction())
        self.menubar.addAction(self.menuNew_model.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Tab 2"))
        self.datasetsLabel.setText(_translate("MainWindow", "Datasets"))
        self.modelsLabel.setText(_translate("MainWindow", "Models"))
        self.menuNew_dataset.setTitle(_translate("MainWindow", "New dataset"))
        self.menuNew_model.setTitle(_translate("MainWindow", "New model"))
