# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchDialog(object):
    def setupUi(self, SearchDialog):
        SearchDialog.setObjectName("SearchDialog")
        SearchDialog.resize(590, 747)
        self.gridLayout = QtWidgets.QGridLayout(SearchDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.files = QtWidgets.QTreeWidget(SearchDialog)
        self.files.setObjectName("files")
        self.gridLayout.addWidget(self.files, 0, 0, 1, 1)
        self.progbar = QtWidgets.QProgressBar(SearchDialog)
        self.progbar.setProperty("value", 0)
        self.progbar.setObjectName("progbar")
        self.gridLayout.addWidget(self.progbar, 1, 0, 1, 1)
        self.statusMessage = QtWidgets.QLabel(SearchDialog)
        self.statusMessage.setObjectName("statusMessage")
        self.gridLayout.addWidget(self.statusMessage, 2, 0, 1, 1)

        self.retranslateUi(SearchDialog)
        QtCore.QMetaObject.connectSlotsByName(SearchDialog)

    def retranslateUi(self, SearchDialog):
        _translate = QtCore.QCoreApplication.translate
        SearchDialog.setWindowTitle(_translate("SearchDialog", "Dialog"))
        self.files.headerItem().setText(0, _translate("SearchDialog", "Name"))
        self.files.headerItem().setText(1, _translate("SearchDialog", "Path"))
        self.files.headerItem().setText(2, _translate("SearchDialog", "Binary code"))
        self.files.headerItem().setText(3, _translate("SearchDialog", "Hamming distance"))
        self.statusMessage.setText(_translate("SearchDialog", "Starting search..."))
